# Generated by Django 4.1.3 on 2022-11-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment5app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1998-12-31'),
            preserve_default=False,
        ),
    ]
